import { Injectable } from '@angular/core';
import { Storage } from '@ionic/storage';

export interface Song {
  name: string,
  nativeURL: string,
  numberOfPlaybacks: number,
  imageURL: string,
  size: number,
  length: number,
  favourite: boolean,
  isMarkedForDeletion: boolean
}

@Injectable()
export class PersistenceService {

  constructor(private storage: Storage) {
    this.persistSongs(); // remove later
  }
  
  public getSongs(): Promise<any> {
    return this.storage.get('songs');
  }

  public persistSongs() {
    let songs = {
      songs: [ 
        { name: 'Coma - Sierpien',
          nativeURL: 'TBD',
          numberOfPlaybacks: 10,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Magda',
          nativeURL: 'TBD',
          numberOfPlaybacks: 229,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Nie wierze skurwysynom',
          nativeURL: 'TBD',
          numberOfPlaybacks: 254,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Listopad',
          nativeURL: 'TBD',
          numberOfPlaybacks: 950,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Spadam',
          nativeURL: 'TBD',
          numberOfPlaybacks: 425,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Proste Decyzje',
          nativeURL: 'TBD',
          numberOfPlaybacks: 338,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Leszek Zukowski',
          nativeURL: 'TBD',
          numberOfPlaybacks: 694,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Wrony',
          nativeURL: 'TBD',
          numberOfPlaybacks: 905,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Zaprzepaszczone sily wielkiej armii swietych znakow',
          nativeURL: 'TBD',
          numberOfPlaybacks: 324,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Pierwsze wyjscie z mroku',
          nativeURL: 'TBD',
          numberOfPlaybacks: 349,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Moscow',
          nativeURL: 'TBD',
          numberOfPlaybacks: 913,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Popoludnia bezkarnie cytrynowe',
          nativeURL: 'TBD',
          numberOfPlaybacks: 569,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Lajki',
          nativeURL: 'TBD',
          numberOfPlaybacks: 350,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Odwolane',
          nativeURL: 'TBD',
          numberOfPlaybacks: 191,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
        { name: 'Coma - Sto tysiecy jednakowych miast',
          nativeURL: 'TBD',
          numberOfPlaybacks: 867,
          imageURL: 'TBD',
          size: 6908493,
          length: 423,
          favourite: true,
          isMarkedForDeletion: false},
      ]
    }
    this.storage.set('songs', songs);
  }

}
