export type DISPLAY_MODES = 'LIST' | 'DETAIL';
export const DISPLAY_MODES = {
  LIST: 'LIST' as DISPLAY_MODES,
  DETAIL: 'DETAIL' as DISPLAY_MODES
};

export type SORT_MODES = 'NO_SORT' | 'NAME_ASCENDING' | 'NAME_DESCENDING' | 'PLAYED_ASCENDING' | 'PLAYED_DESCENDING';
export const SORT_MODES = {
  NO_SORT: 'NO_SORT' as SORT_MODES,
  NAME_ASCENDING: 'NAME_ASCENDING' as SORT_MODES,
  NAME_DESCENDING: 'NAME_DESCENDING' as SORT_MODES,
  PLAYED_ASCENDING: 'PLAYED_ASCENDING' as SORT_MODES,
  PLAYED_DESCENDING: 'PLAYED_DESCENDING' as SORT_MODES
};

export type REPEAT_MODES = 'NONE' | 'SONG' | 'PART_OF_SONG' | 'SELECTED' | 'FAVOURITE' | 'ALL';
export const REPEAT_MODES = {
  NONE: 'NONE' as REPEAT_MODES,
  SONG: 'SONG' as REPEAT_MODES,
  PART_OF_SONG: 'PART_OF_SONG' as REPEAT_MODES,
  SELECTED: 'SELECTED' as REPEAT_MODES,
  FAVOURITE: 'FAVOURITE' as REPEAT_MODES,
  ALL: 'ALL' as REPEAT_MODES
};
